apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ort-postgres.fullname" . }}
  labels:
    {{- include "ort-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ort-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ort-postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.containerPort.name  }}
              containerPort: {{ .Values.containerPort.port }}
              protocol: TCP
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: postgres-pv-claim
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: postgres-pv-claim
          {{- else }}
            emptyDir: {}
          {{- end -}}