apiVersion: v1
kind: Service
metadata:
  name: {{ include "ort-postgres.fullname" . }}
  labels:
    {{- include "ort-postgres.selectorLabels" . | nindent 4 }}

spec:
  ports:
  - name: {{ .Values.containerPort.name  }}
    port: {{ .Values.containerPort.port }}
    targetPort: {{ .Values.containerPort.name  }}
  selector:
    {{- include "ort-postgres.selectorLabels" . | nindent 4 }}
    